---
- name: "Pre-upgrade | check if old credential dir exists"
  stat:
    path: "{{ inventory_dir }}/../credentials"
  delegate_to: localhost
  register: old_credential_dir
  become: no

- name: "Pre-upgrade | check if new credential dir exists"
  stat:
    path: "{{ inventory_dir }}/credentials"
  delegate_to: localhost
  register: new_credential_dir
  become: no
  when: old_credential_dir.stat.exists

- name: "Pre-upgrade | move data from old credential dir to new"
  command: mv {{ inventory_dir }}/../credentials {{ inventory_dir }}/credentials
  args:
    creates: "{{ inventory_dir }}/credentials"
  delegate_to: localhost
  become: no
  when:
    - old_credential_dir.stat.exists
    - not new_credential_dir.stat.exists

- name: "Pre-upgrade | check if old certificate dir exists"
  stat:
    path: "{{ kube_config_dir }}/ssl"
  register: old_certificate_dir
  become: yes

- name: "Pre-upgrade | check if new certificate dir exists"
  stat:
    path: "{{ kube_cert_dir }}"
  register: new_certificate_dir
  become: yes
  when: old_certificate_dir.stat.exists

- name: "Pre-upgrade | move data from old certificate dir to new"
  command: mv {{ kube_config_dir }}/ssl {{ kube_cert_dir }}
  args:
    creates: "{{ kube_cert_dir }}"
  become: yes
  when:
    - old_certificate_dir.stat.exists
    - not new_certificate_dir.stat.exists
